services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    restart: always
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - my_network
    restart: always
    volumes:
      - .:/var/www
    environment:
      port: 8080
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 8080:8080
networks:
  my_network:
    driver: bridge
volumes:
  db_data: