

      - name: Checkout php
        uses: actions/checkout@v4

      - name: Setup Env
        run:  |
          cp .env.ci .env

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{inputs.version}}