name: "Setup PHP Environment"
description: "Checkout code, setup environment, and configure PHP with PECL extension"
inputs:
  version:
    description: "The PHP version to setup"
    required: true
    default: "8.2"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: cp .env.ci .env

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.version }}