name: "Main Workflow"
on:
    push:
      branches:
        - dev
    pull_request:
      branches:
        - dev
        - main
jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports: 
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
    steps: 
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout php
        uses: actions/checkout@v4

      - name: Setup Env
        run:  |
          cp .env.ci .env

      - name: Install dependencies
        run: 
          composer install

      - name: Generate the Key
        run: 
          php artisan key:generate

      - name: debug the container
        run:
          docker ps

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          username: Techrepos
          password: Blur123!@#