name: "Main Workflow"
on:
    push:
      branches:
        - dev
jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps: 
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout php
        uses: actions/checkout@v4

      - name: Setup Env
        run:  |
          cp .env.ci .env

      - name: Install dependencies
        run: 
          composer install

      - name: Generate the Key
        run: 
          php artisan key:generate

      - name: Run Mysql
        run:
          docker run -d -p 3306:3306 -e DB_CONNECTION=mysql -e DB_HOST=127.0.0.1 -e DB_PORT=3306 -e DB_DATABASE=test -e DB_USERNAME=root -e DB_PASSWORD=password mysql:latest

      - name: debug the container
        run:
          docker ps
      
      - name: Migrate the Database
        run:
          php artisan migrate

      - name: Run unit testing
        run: |
          php artisan test