name: "Main Workflow"
on:
    push:
      branches:
        - dev
    pull_request:
      branches:
        - dev
        - main
jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps: 
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout php
        uses: actions/checkout@v4

      - name: Setup Env
        run:  |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Install dependencies
        run: 
          composer install

      - name: Cache the app dependencies
        uses: actions/cache@v4.0.2
        with:
          key: ${{ github.sha }}-php-vendor-cache
          path: ./vendor

      - name: Generate the Key
        run: 
          php artisan key:generate
  
  test:
    name: Test Laravel App
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mysql:latest
        ports: 
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - name: Setup Env
        run:  |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # - name: Install dependencies
      #   run: 
      #     composer install

      - name: Restore the cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./vendor
          key: php-vendor-cache

      - name: Composer install
        if: steps.cache.outputs.cache-hit != true
        run:
          composer install

      - name: Generate the Key
        run: 
          php artisan key:generate

      # - name: Migrate the database
      #   run:
      #     php artisan migrate
          
      - name: debug the container
        run:
          docker ps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest
          