name: "Main Workflow"

on:
    push:
    pull_request:
      branches:
        - dev
        - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  
  test:
    name: Test Laravel App
    needs: [build]
    uses: ./.github/workflows/test.yaml
    