name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
    secrets:
      required-secrets:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Setup Env
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Install dependencies
        run: composer install

      
